repos:
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.17.5  
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0  
    hooks:
      - id: isort
        args: ["--profile", "black"]
